### PR TITLE
feat: add `--continue` for wget download

### PR DESCRIPTION
**Pull request by genffy**
the same as https://github.com/facebookresearch/llama/pull/441 but add more

### CODE REVIEW

**Comment by AminulBD** [comment]
This should be merged.

**Comment by hatala91** [comment]
Thanks @genffy! A similar change was introduced with PR #738. Could you kindly check if that covers the changes proposed here?

**Comment by genffy** [comment]
> Thanks @genffy! A similar change was introduced with PR #738. Could you kindly check if that covers the changes proposed here?

ok, updated missing changes

**Comment by samuelselvan** [comment]
@genffy I just merged #822, am hoping that would take care of the intent of this PR.

**Pull request closed without merging**
