### PR TITLE
Update download.sh

### PR DESCRIPTION
**Pull request by Ameero11**

### CODE REVIEW

**Review by Inserian — COMMENTED** [review]
I'm not sure what the point to this is?

**Comment by MAvoss** [comment]
LGTM

**Review by Inserian — CHANGES_REQUESTED** [review]
This doesn't need to be altered.

**Comment by Jainam213** [comment]
LGTM!

**Comment by huzpsb** [comment]
LGTM

**Review by antonkesy — CHANGES_REQUESTED** [review]
Nope

**Comment by hatala91** [comment]
Hey @Ameero11! There are three similar PRs #113 #114 #116. As pointed out these look like accidental commits/ PRs and given that there has been no activity for ~5 months I'll close them for now.

However, feel free to re-open or reach out if I got that wrong.

**Pull request closed without merging**
