### PR TITLE
Update README.md - Fixed some minor grammatical issues.

### PR DESCRIPTION
**Pull request by ShorthillsAI**
Fixed some minor grammatical issues.

### CODE REVIEW

**Review by jspisak — APPROVED** [review]
These look good - thanks for the edits!

**Comment by mykolasolodukha** [comment]
@ShorthillsAI probably while fixing some minor grammatical issues, some major syntax issues have been introduced 👀 

On line 37, is `pip install -e.` a correct way to run the `pip install` command here?

**Comment by ShorthillsAI** [comment]
@mykolasolodukha Apologies for the same i have Undo that changes under the [PR](https://github.com/facebookresearch/llama/pull/1058)

**Comment by jspisak** [comment]
nw - i can take a look at the new PR and merge the undo. easy peasy!

**Pull request merged**
