### PR TITLE
make download.sh executable

### PR DESCRIPTION
**Pull request by dangbert**

### CODE REVIEW

**Comment by dangbert** [comment]
Question for developers: shall we add `set -e` to download.sh to make it stop on the first error?

**Comment by ckxng** [comment]
I agree, if we fail to create the directory, then we will start downloading files into unexpected locations when the `cd` that comes later fails too.

**Review by hatala91 — APPROVED** [review]
Thanks, lgtm! Tested locally that this works.

**Comment by ckxng** [comment]
ship it

**Comment by anynomousaccount** [comment]
Hello, nice! I have a question, **how to change the .sh file to be executable**? 
I noticed the download.sh only added `set -e`,  which seems unrelated to making the file executable.

**Comment by dangbert** [comment]
> Hello, nice! I have a question, **how to change the .sh file to be executable**? I noticed the download.sh only added `set -e`, which seems unrelated to making the file executable.

You're correct that `set -e` is irrelevant. However if you check the diff in this PR you're also see that the file mode changed from 100644 -> 100755 which is what makes this file executable.

So this file should be executable now unless someone changed it in another PR.

**Comment by dangbert** [comment]
To be more clear, a file is made executable with a command like `chmod a+x filename.txt`

**Comment by anynomousaccount** [comment]
> > Hello, nice! I have a question, **how to change the .sh file to be executable**? I noticed the download.sh only added `set -e`, which seems unrelated to making the file executable.
> 
> You're correct that `set -e` is irrelevant. However if you check the diff in this PR you're also see that the file mode changed from 100644 -> 100755 which is what makes this file executable.
> 
> So this file should be executable now unless someone changed it in another PR.

Got it! Very clear, thanks!

**Pull request merged**
